### ISSUE TITLE
Aspect ratio 1:1 (square), it turns out not square

### ISSUE THREAD

**Issue by tweaker** [ArthurHub/Android-Image-Cropper#48] opened 2016-04-08 08:30 UTC
Hello!
Sorry for my English.

I set the aspect ratio of 1: 1 (square), and the width and height of the cropped images are different. It turns out that in the end we did not square.

How can I solve this problem?

> cropImageView = (CropImageView) findViewById(R.id.cropImageView);
cropImageView.setImageUriAsync(imageUri);
cropImageView.setAspectRatio(1, 1);
cropImageView.setFixedAspectRatio(true);
cropImageView.setGuidelines(CropImageView.Guidelines.ON);
cropImageView.setScaleType(ImageView.ScaleType.FIT_CENTER);
...
Rect rect = cropImageView.getActualCropRect();
Log.i(Const.Debug.DEBUG_TAG, "Actual crop rect: " + rect);
Log.i(Const.Debug.DEBUG_TAG, "Actual crop rect.left: " + rect.left);
Log.i(Const.Debug.DEBUG_TAG, "Actual crop rect.top: " + rect.top);
Log.i(Const.Debug.DEBUG_TAG, "Actual crop rect.right: " + rect.right);
Log.i(Const.Debug.DEBUG_TAG, "Actual crop rect.bottom: " + rect.bottom);
Log.i(Const.Debug.DEBUG_TAG, "Actual crop rect.width: " + rect.width());
Log.i(Const.Debug.DEBUG_TAG, "Actual crop rect.height: " + rect.height());

> Actual crop rect: Rect(450, 0 - 2685, 2234)
Actual crop rect.left: 450
Actual crop rect.top: 0
Actual crop rect.right: 2685
Actual crop rect.bottom: 2234
Actual crop rect.width: 2235
Actual crop rect.height: 2234
....
Actual crop rect: Rect(226, 1161 - 2461, 3395)
Actual crop rect.left: 226
Actual crop rect.top: 1161
Actual crop rect.right: 2461
Actual crop rect.bottom: 3395
Actual crop rect.width: 2235
Actual crop rect.height: 2234

**Comment by ArthurHub** [comment] 2016-04-09 08:10
classic off-by-1 bug :)
fixed in **v1.2.5**

**Closed by ArthurHub** 2016-04-09 08:10 UTC
Labels: bug

**Comment by tweaker** [comment] 2016-04-09 08:30
Thank you very much for your efficiency!
But some coordinates still manifests the bug that the height is greater than the width:
As I understand it, in some cases, to the height of 1px flops

```
Actual crop rect: Rect(419, 626 - 2847, 3053)
Actual crop rect.left: 419
Actual crop rect.top: 626
Actual crop rect.right: 2847
Actual crop rect.bottom: 3053
Actual crop rect.width: 2428
Actual crop rect.height: 2427

Actual crop rect: Rect(0, 321 - 2847, 3167)
Actual crop rect.left: 0
Actual crop rect.top: 321
Actual crop rect.right: 2847
Actual crop rect.bottom: 3167
Actual crop rect.width: 2847
Actual crop rect.height: 2846
```

**Comment by ArthurHub** [comment] 2016-04-09 08:44
are you sure you updated to 1.2.5?
I'm unable to reproduce it now.

**Comment by tweaker** [comment] 2016-04-09 08:54
Yes I updated to version 1.2.5.
Also cleared the project, deleted from the phone app and reinstalled everything.
Previously, it was the inaccuracy of 1-2 pixels. Now only 1 pixel.
The bug manifests itself only in **portrait** mode.

My template:

```
<com.theartofdev.edmodo.cropper.CropImageView xmlns:custom="http://schemas.android.com/apk/res-auto"
            android:id="@+id/cropImageView"
            android:layout_width="0dp"
            android:layout_height="match_parent"
            android:layout_weight="1"
            android:background="@drawable/rect_cropper"
            custom:cropInitialCropWindowPaddingRatio="0"
            custom:cropMinCropResultHeightPX="700"
            custom:cropMinCropResultWidthPX="700"
            custom:cropScaleType="fitCenter" />
```

**Comment by tweaker** [comment] 2016-04-09 09:13
And not just in the horizontal position of a difference there is in 2 pixel:

```
Actual crop rect: Rect(0, 0 - 2850, 2848)
Actual crop rect.left: 0
Actual crop rect.top: 0
Actual crop rect.right: 2850
Actual crop rect.bottom: 2848
Actual crop rect.width: 2850
Actual crop rect.height: 2848
```

**Comment by ArthurHub** [comment] 2016-04-09 11:22
sorry, totally missed that it can be off by 2 =/
please try **1.2.6**, let me know if it works

**Comment by tweaker** [comment] 2016-04-09 12:30
Everything works fine! Thank you very much for your help!

![photo_2016-04-09_20-27-50](https://cloud.githubusercontent.com/assets/3106164/14403612/27744774-fe9a-11e5-8636-26a70038a19a.jpg)
