### ISSUE TITLE
Crop Button disappears on second time.

### ISSUE THREAD

**Issue by honey-hoper** [ArthurHub/Android-Image-Cropper#350] opened 2017-08-01 06:53 UTC
![screenshot_1501570222](https://user-images.githubusercontent.com/29705143/28812778-f73ebe5c-76b3-11e7-9ce9-2fe30a078116.png)
![screenshot_1501570230](https://user-images.githubusercontent.com/29705143/28812784-fc1333a4-76b3-11e7-8079-e2d2a2a7d5ee.png)

Crop Button appears for the first time the activity is launched after that is does not shows up.

**Comment by honey-hoper** [comment] 2017-08-01 06:54
The button still works but the text dissappears.

**Comment by ghanendrapiplani** [comment] 2017-08-03 07:38
I am having the same issue, in my case the button is not visible in the first run of the app, the button was showing sometime back , but in recent builds i am noticing the button is invisible! please need resolution fast or i will have to remove this library!

**Comment by ArthurHub** [comment] 2017-08-04 07:17
Android... 
It's something in this code: https://github.com/ArthurHub/Android-Image-Cropper/blob/master/cropper/src/main/java/com/theartofdev/edmodo/cropper/CropImageActivity.java#L131
can you debug and see what going on there?
I can't reproduce it so it's a bit hard for me

**Comment by ArthurHub** [comment] 2017-09-01 15:59
fixed in v2.5.0

**Closed by ArthurHub** 2017-09-01 15:59 UTC
