### ISSUE TITLE
Zoom image show when taking picture from camera

### ISSUE THREAD

**Issue by arpitjoshi08** [ArthurHub/Android-Image-Cropper#103] opened 2016-06-22 06:15 UTC
i am using this library, its working fine but only getting issue when i captured image from camera... 
when i am taking image from camera then goes for crop ,its automatically zoom image show. is there any solution for that? and working proper when take from gallery.

**Comment by ArthurHub** [comment] 2016-06-22 07:23
Can you post the code you use to create capture image from camera, get the captured uri and how you set it for cropping.

**Comment by arpitjoshi08** [comment] 2016-06-22 07:31
i use this code for open dialog 
`  public void onSelectImageClick() {
        Utils.keyboardHide(this);
        CropImage.startPickImageActivity(this);
    }`

then  for cropping
` private void startCropImage(Uri imageUri) {
        CropImage.activity(imageUri)
                .setGuidelines(CropImageView.Guidelines.ON).setFixAspectRatio(true)
                .start(this);
    }`

and then 
` @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if (requestCode == CropImage.PICK_IMAGE_CHOOSER_REQUEST_CODE && resultCode == Activity.RESULT_OK) {
            Uri imageUri = CropImage.getPickImageResultUri(this, data);
            startCropImage(imageUri);
        }
        // handle result of CropImageActivity
        if (requestCode == CropImage.CROP_IMAGE_ACTIVITY_REQUEST_CODE) {
            CropImage.ActivityResult result = CropImage.getActivityResult(data);
            resultUri = result;
            if (resultCode == RESULT_OK) {
                loadImage(profileImageView, result.getUri().getPath());

            } else if (resultCode == CropImage.CROP_IMAGE_ACTIVITY_RESULT_ERROR_CODE) {
                Toast.makeText(this, "Cropping failed: " + result.getError(), Toast.LENGTH_LONG).show();
            }
        }
    }`

**Comment by ArthurHub** [comment] 2016-06-22 07:35
do you see the same issue when you run the sample app?

**Comment by arpitjoshi08** [comment] 2016-06-22 07:36
i have to check sir..please wait for 15 minutes i will check this issue in sample app...

**Comment by arpitjoshi08** [comment] 2016-06-22 07:56
i checked in sample app it is fix...no option to zoom image when capture image or fetch from gallery so not possible to check it properly

**Comment by ArthurHub** [comment] 2016-06-22 07:58
hmmm.... I'm not sure what you mean by zoom, you are not talking about the auto-zoom feature of the library it seems.

**Comment by arpitjoshi08** [comment] 2016-06-22 09:42
i think problem is in my code....so please close this issue and thanks for help...i checked the sample app properly and with changes its working fine..thanks sir

**Comment by ArthurHub** [comment] 2016-06-22 09:45
No problem, happy to be of some help, it is always good to check with a working code sample.
It will be also great to explain in a few words what was the issue, other people may encounter it and reach this page via google.
Feel free to close the issue yourself too :)

**Comment by arpitjoshi08** [comment] 2016-06-22 09:56
![screenshot_2016-06-22-15-20-55](https://cloud.githubusercontent.com/assets/17329682/16262553/b8328f14-388d-11e6-894e-478ee02ca9ed.png)
my captured image like this

**Comment by arpitjoshi08** [comment] 2016-06-22 09:57
![screenshot_2016-06-22-15-20-37](https://cloud.githubusercontent.com/assets/17329682/16262574/cca24430-388d-11e6-82f7-bc8f34179615.png)
after captured its showing like this...

**Comment by ashishCDN0135** [comment] 2016-06-22 10:00
ya same problem with me after pressing save it takes complte zoom

**Comment by arpitjoshi08** [comment] 2016-06-22 10:01
this is my issue. i want same image show without zoom for crop after capturing from camera

**Comment by ashishCDN0135** [comment] 2016-06-22 10:13
heyy arpit in the sample app it works properly but at the same time same code it gives issues as u mentioned earlier...ny help will be really apriciated

**Comment by arpitjoshi08** [comment] 2016-06-22 11:39
ArthurHub  i am not closing issue this time because i am getting issue still yet.. i shared images so please check ..

**Comment by ArthurHub** [comment] 2016-06-22 14:24
what's different between your code and the sample app?
maybe something in initialization...

**Comment by arpitjoshi08** [comment] 2016-06-24 11:49
Sorry for late reply  .... i used this setAutoZoomEnabled(false) now its working properly thanks  ArthurHub  for help ....

**Comment by ArthurHub** [comment] 2016-06-24 12:52
You just disabled the auto-zoom feature :(

It is possible that there is a bug in the library but I don't understand how to reproduce it... you said that you can't reproduce it in the sample app because "no option to zoom image when capture image", I have no idea what it means...

@ashishCDN0135 also mentioned he has this issue so probably it is a thing, but he didn't give any more info to go on...

This make me very sad :disappointed:

**Comment by arpitjoshi08** [comment] 2016-06-24 13:11
actually ArthurHub there were two sample app in this module on the time of my comment i was tested second sample app which contain only function of taking picture from gallery and camera....then i checked next one which contain all also included zoom of or on ....so sorry for that..for me library so helpful and working properly in my code ...thanks for help....and close this issue

**Closed** 2016-06-24 13:25 UTC
